name: Wukong
targets:
  Wukong:
    type: application
    platform: iOS
    sources:
    - Client
    - UI
    - Resource
    dependencies:
    - carthage: Cartography
    - carthage: SwiftWebSocket
    - carthage: Eureka
    settings:
      SWIFT_VERSION: '4.2'
      IPHONEOS_DEPLOYMENT_TARGET: '11.0'
